repos:
  - repo: local
    hooks:
      - id: dune-format
        name: Auto format with dune
        entry: dune fmt --auto
        language: system
        files: \.(ml|mli|mll|mly)$
        stages: [pre-commit]
        pass_filenames: false

      - id: remove-claude-attribution
        name: Remove Claude attribution from commit message
        entry: python3 .hooks/remove-claude-lines.py
        language: system
        stages: [commit-msg]
